site_name: vcfstats
theme:
    name: 'material'
    font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
nav:
    - 'Introduction': 'index.md'
    - 'Command-line arguments': 'cliargs.md'
    - 'Configuration file': 'configfile.md'
    - 'Formulas': 'formulas.md'
    - 'Macros': 'macros.md'
    - 'Change log': 'CHANGELOG.md'
